- name: Installing the apache package
  package:
          name: "{{ web_pack }}"
          state: present
  register: pk


- name: Copy the web content
  template:
          src: "main.html.j2"
          dest: "/var/www/html/main.html"

- name: Copy the template from src file
  template:
          src: "{{ httpd_config_file }}"
          dest: /etc/httpd/conf.d/user.conf
          owner: root
          group: root
          mode: '0664'
  notify: web_restart

- name: Ensuring service to be started
  service:
          name: "{{ service_name }}"
          state: started
  register: srv
  when: ansible_distribution == "Ubuntu"

- name: Ensuring service to be started
  service:
          name: "{{ service1_name }}"
          state: started

- name: Allowing service to pass firewalld
  firewalld:
          port: "{{ port_no }}"
          state: enabled
          permanent: yes
          immediate: yes

- name: Allowing service to pass firewalld
  firewalld:
          service: http
          state: enabled
          permanent: yes
  notify: firewall_restart

- debug:
        var: pk.rc
- debug:
        msg: "service {{ service_name }} has been started"

